addressbook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
import contacts.views

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^$', contacts.views.ListContactView.as_view(),
                           name='contacts-list',),
                       url(r'^tasks/', include('contacts.urls',
                                               namespace='contacts')),
                       url(r'^login/$', 'django.contrib.auth.views.login'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout'),
                       )
urlpatterns += staticfiles_urlpatterns()

contacts/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
                       url(r'^$', views.ListContactView.as_view(),
                           name='contacts-list',),
                       url(r'^new$', views.CreateContactView.as_view(),
                           name='contacts-new',),
                       url(r'^edit/(?P<pk>\d+)/$',
                           views.UpdateContactView.as_view(),
                           name='contacts-edit',),
                       url(r'^delete/(?P<pk>\d+)/$',
                           views.DeleteContactView.as_view(),
                           name='contacts-delete',),
                       url(r'^(?P<pk>\d+)/$', views.ContactView.as_view(),
                           name='contacts-view',),
                       url(r'^edit/(?P<pk>\d+)/addresses$',
                           views.EditContactAddressView.as_view(),
                           name='contacts-edit-addresses',),
                       )

contacts/models.py
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db import models


class Contact(models.Model):
    first_name = models.CharField(
        max_length=255,
    )
    last_name = models.CharField(
        max_length=255,
    )
    email = models.EmailField()
    owner = models.ForeignKey(User)

    def __str__(self):
        return ' '.join([
            self.first_name,
            self.last_name,
        ])

    def get_absolute_url(self):
        return reverse('contacts:contacts-view', kwargs={'pk': self.id})


class Address(models.Model):
    contact = models.ForeignKey(Contact)
    address_type = models.CharField(
        max_length=10,
    )
    address = models.CharField(
        max_length=255,
    )
    city = models.CharField(
        max_length=255,
    )
    state = models.CharField(
        max_length=2,
    )
    postal_code = models.CharField(
        max_length=20,
    )

    class Meta:
        unique_together = ('contact', 'address_type',)


class TestModel(models.Model):
    first_field = models.CharField(max_length=255)
    second_field = models.CharField(max_length=255)

contacts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import inlineformset_factory
from .models import Contact, Address


class ContactForm(forms.ModelForm):
    confirm_email = forms.EmailField(
        label="Confirm email",
        required=True,
    )

    class Meta:
        model = Contact

    def __init__(self, *args, **kwargs):
        if kwargs.get('instance'):
            email = kwargs['instance'].email
            kwargs.setdefault('initial', {})['confirm_email'] = email
        return super(ContactForm, self).__init__(*args, **kwargs)

    def clean(self):
        if (self.cleaned_data.get('email') !=
                self.cleaned_data.get('confirm_email')):
            raise ValidationError(
                "Email addresses must match."
            )
        return self.cleaned_data

# inlineformset_factory creates a Class from a parent model (Contact)
# to a child model (Address)
ContactAddressFormSet = inlineformset_factory(
    Contact,
    Address,
)

contacts/views.py
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from .models import Contact
from .forms import ContactForm, ContactAddressFormSet


class LoggedInMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(*args, **kwargs)


class ListContactView(ListView):
    model = Contact

    def get_queryset(self):
        return Contact.objects.filter(owner=self.request.user.id)


class CreateContactView(CreateView):
    model = Contact
    form_class = ContactForm

    def get_success_url(self):
        return reverse('contacts:contacts-list')

    def get_context_data(self, **kwargs):
        context = super(CreateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts:contacts-new')
        return context


class UpdateContactView(UpdateView):
    model = Contact
    form_class = ContactForm

    def get_success_url(self):
        return reverse('contacts:contacts-list')

    def get_context_data(self, **kwargs):
        context = super(UpdateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts:contacts-edit',
                                    kwargs={'pk': self.get_object().id})
        return context


class DeleteContactView(DeleteView):
    model = Contact

    def get_success_url(self):
        return reverse('contacts:contacts-list')


class ContactView(DetailView):
    model = Contact

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        queryset = queryset.filter(
            pk=pk,
            owner=self.request.user,
        )
        try:
            obj = queryset.get()
        except ObjectDoesNotExist:
            raise Http404((u"No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        return obj


class EditContactAddressView(UpdateView):
    model = Contact
    template_name = 'contacts/edit_addresses.html'
    form_class = ContactAddressFormSet

    def get_success_url(self):
        # redirect to the Contact view.
        return self.get_object().get_absolute_url()

templates/contacts/base.html
{% load staticfiles %}
<html>
  <head>
    <link href="{% static 'contacts/css/bootstrap.min.css' %}"
          rel="stylesheet" media="screen">
  </head>
  <body>
      <div>
          {{ user }}
          {% if user.is_anonymous %}
              <a href="{% url 'django.contrib.auth.views.login' %}">login</a>
          {% else %}
              <a href="{% url 'django.contrib.auth.views.logout' %}">logout</a>
          {% endif %}
      </div>
      {% block content %}
      {% endblock %}
      <script src="{% static 'contacts/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/contacts/contact_confirm_delete.html
{% extends "contacts/base.html" %}

{% block content %}
    <h1>Delete Contact</h1>
    <p>Are you sure you want to delete the contact {{ contact }}?</p>
    <form action="{% url "contacts:contacts-delete" pk=contact.id %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="Yes, delete." />
      <a href="{% url "contacts:contacts-list" %}">No, cancel.</a>
    </form>
{% endblock %}

templates/contacts/contact_detail.html
{% extends "contacts/base.html" %}

{% block content %}
    <h1>{{ contact }}</h1>
    <p>Email: {{ contact.email }}</p>
    <ul>
    {% for address in contact.address_set.all %}
       <li>{{ address.address }}<br/>
           {{ address.city }} {{ address.state }}<br/>
           {{ address.postal_code }}
       </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/contacts/contact_form.html
{% extends "contacts/base.html" %}

{% block content %}
    {% if contact.id %}
        <h1>Edit Contact</h1>
    {% else %}
        <h1>Add Contact</h1>
    {% endif %}
    <form action="{{ action }}" method="POST">
      {% csrf_token %}
      {% if form.non_field_errors %}
        <ul>
          {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
      {% for field in form %}
      <div id="{{ field.auto_id }}_container">
        {{ field.help_text }}
        <div>
          {{ field.label_tag }} {{ field }}
        </div>
        <div id="{{ field.auto_id }}_errors">
          {{ field.errors }}
        </div>
      </div>
      {% endfor %}
      <input id="save_contact" type="submit" value="Save" />
    </form>
    {% if contact.id %}
    <a href="{% url "contacts:contacts-edit-addresses" pk=contact.id %}">
      Edit Addresses
    </a>
    <a href="{% url "contacts:contacts-delete" pk=contact.id %}">Delete</a>
    {% endif %}
    <a href="{% url "contacts:contacts-list" %}">back to list</a>
{% endblock %}

templates/contacts/contact_list.html
{% extends "contacts/base.html" %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Contacts</h1>
        {% for contact in object_list %}
        <li class="contact">
            <a href="{{ contact.get_absolute_url }}">{{ contact }}</a>
            (<a href="{% url "contacts:contacts-edit" pk=contact.id %}">edit</a>)
        </li>
        {% endfor %}
            <a href="{% url "contacts:contacts-new" %}">add contact</a>
    {% else %}
        <p>Please, log in to add new contact. Login - "admin". Password - "admin"</p>
    {% endif %}
{% endblock %}

templates/contacts/edit_addresses.html
{% extends "contacts/base.html" %}

    {% block content %}
    <h1>Edit Addresses</h1>
    <p>Editing addresses for {{ contact }}</p>
    <form action="{% url "contacts:contacts-edit-addresses" pk=contact.id %}"
          method="POST">
        {% csrf_token %}
        {{ form.management_form }}
        {% for address_form in form %}
            <ul>
            {{ address_form.as_ul }}
            </ul>
        {% endfor %}
        <input type="submit" value="Save" />
    </form>
{% endblock %}